# .buildkite/cache.yml
dependencies:
  - id: "js_cache"
    key: "{{ id }}-{{ agent.os }}-{{ agent.arch }}-{{ checksum \"package-lock.json\" }}"
    fallback_keys":
      - "{{ id }}-{{ agent.os }}-{{ agent.arch }}-"
      - "{{ id }}-"
    paths:
      - "node_modules"
