common:
  - buildkite_cache: &buildkite-cache
      buildkite/zstash:
        ids: "js-cache" # comma seperated list of caches

image: "sorchaabel/nodejs-pipeline-example:1.0"
steps:
  - name: ":node:"
    command: |
      "npm install"
      "npm test"
    plugins: [*buildkite-cache]
